import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ConstantData {
  visitorData = [
    { name: "STRESS TEST" },
    { name: "COLOR DOPPLER" },
    { name: "ECG" },
    { name: "Digital X-ray" },
    { name: "Digital Mammography" },
    { name: "O.P.G" },
    { name: "CT Scan" },
    { name: "MRI" },
    { name: "PET Scan" },
    { name: "2D Echo" },
    { name: "PFT" },
    { name: "EEG" },
    { name: "HEAMOGLOBIN" },
    { name: "C.B.C." },
    { name: "E.S.R." },
    { name: "MALARIA TEST (M.P.)" },
    { name: "BLOOD GROUP & RH FACTOR" },
    { name: "PLATELET COUNT" },
    { name: "G6PD" },
    { name: "SICKLING TEST" },
    { name: "PROTHROMBIN TIME/PTT" },
    { name: "BLEEDING & CLOTTING TIME" },
    { name: "BLOOD SUGAR FASTING" },
    { name: "BLOOD SUGAR POST LUNCH" },
    { name: "BLOOD SUGAR RANDOM" },
    { name: "G.T.T.(4 SAMPLE)" },
    { name: "BLOOD UREA" },
    { name: "BUN" },
    { name: "SERUM CREATININE" },
    { name: "SERUM ELECTROLYTE" },
    { name: "R.F.T." },
    { name: "TOTAL PROTEIN" },
    { name: "URIC ACID" },
    { name: "ALBUMINE/GLOBUMINE" },
    { name: "SERUM ELECTROLYTE" },
    { name: "ALKALINE PHOSPHATE" },
    { name: "S.G.O.T." },
    { name: "S.G.P.T." },
    { name: "BILIRUBINE" },
    { name: "L.F.T." },
    { name: "C.P.K.-MB" },
    { name: "C.P.K.-TOTAL" },
    { name: "CARDIAC PROFILE" },
    { name: "TOTAL CHOLESTEROL" },
    { name: "HDL CHOLESTEROL" },
    { name: "S.G.P.T." },
    { name: "TRIGLYCERIDE" },
    { name: "LIPID PROFILE" },
    { name: "G.G.T." },
    { name: "SERUM AMYLASE" },
    { name: "CALCIUM" },
    { name: "PHOSPHORUS" },
    { name: "MAGNESIUM" },
    { name: "IRON & TIBC" },
    { name: "R.A. TEST" },
    { name: "WIDAL TEST" },
    { name: "V.D.R.L. TEST" },
    { name: "SEMEN ANALYSIS" },
    { name: "HBsAG" },
    { name: "HIV" },
    { name: "HCV" },
    { name: "MANTOUX TEST" },
    { name: "COOMB TEST (DIRECT/INDIRECT)" },
    { name: "WESTERN BLOT TEST" },
    { name: "HLA B-27" },
    { name: "Beta HCG" },
    { name: "TROP T" },
    { name: "T.P.H.A." },
    { name: "T3.T4.TSH" },
    { name: "LH" },
    { name: "FSH" },
    { name: "PROLACTINE" },
    { name: "TOXOPLASMA" },
    { name: "A.S.O. TITRE" },
    { name: "C REACTIVE PROTEIN (CRP)" },
    { name: "SPUTUM A.F.B." },
    { name: "DENGUE IgM/ IgG" },
    { name: "DENGUE NS1" },
    { name: "LEPTOSPIRA IgG/ IgM" },
    { name: "MALERIA ANTIGEN" },
    { name: "IGM" },
    { name: "25-OH Vitamin D" },
    { name: "CA 15.3" },
    { name: "CA 19.9" },
    { name: "CA 125" },
    { name: "G6PD" },
    { name: "Hb1AC" },
    { name: "IRON" },
    { name: "VITAMIN B 12" },
    { name: "URINE ROUTINE" },
    { name: "URINE CULTURE & SENSITIVITY" },
    { name: "PREGNANCY TEST" },
    { name: "URINE SUGAR F/PP" },
    { name: "STOOL ROUTINE" },
    { name: "STOOL CULTURE & SENSITIVITY" },
    { name: "DIABETIC PROFILE" },
    { name: "HYPERTENSION PROFILE" },
    { name: "INFERTILITY PROFILE" },
    { name: "PREGNANCY PROFILE" },
    { name: "HISTOPATHOLOGY" },
    { name: "BLOOD CULTURE" },
    { name: "F.N.A.C." },
    { name: "TROP I" },
    { name: "LIPOPROTEIN - A" },
    { name: "BONE MINERAL DENSITY" },
    { name: "ULTRASOUND" },
    { name: "CRP - HS" },
    { name: "OTHERS" }
  ];


  healthCheckData = [
    { name: "Preventive Health Checkup" },
    { name: "Senior Citizen Health Checkup" },
    { name: "Women's Health Checkup" },
    { name: "Family Health Checkup" },
    { name: "Corporate Health Checkup" },
    { name: "Complete Child Checkup" },
    { name: "School Health Checkup" },
    { name: "Cardiac Health Checkup" },
    { name: "Arthritis Health Checkup" },
    { name: "Diabetes Health Checkup" },
    { name: "Infertility Health Checkup" },
    { name: "Pre-operative Health Checkup" },
    { name: "Cancer Screening Health Checkup" },
    { name: "Residential Health Checkup" },
    { name: "Vitamin Test" },
    { name: "Liver Test" },
    { name: "Anemia Test" },
    { name: "Kidney Test" },
    { name: "Thyroid Test" },
    { name: "PCOD Test" },
    { name: "Other Test" }];

  homeCareData = [
    { name: "Nurse" },
    { name: "Female Attendant" },
    { name: "Male Attendant" },
    { name: "Physiotherapy at Home" },
    { name: "Child Care" },
    { name: "Doctors Visit at Home" },
    { name: "X Ray at Home" },
    { name: "Home ICU Setup" },
    { name: "Special Child Care at Home" },
    { name: "E.C.G. at home" },
    { name: "Oxygen Service at home" },
    { name: "Ambulatory Blood Pressure Services at home" },
    { name: "Ambulance Services" },
    { name: "NRI Home Care" },
    { name: "Elderly Care Services" },
    { name: "Home NICU/PICU Setup" },
    { name: "Wardboy Services" },
    { name: "Home Chemotherapy" },
    { name: "Bed Ridden Care" },
    { name: "Post Hospitalisation Care" },
    { name: "Post Surgery Care" },
    { name: "Cancer/Stroke/Cardiac Care" },
    { name: "Yoga at home" },
    { name: "Fitness Trainer at home" },
    { name: "Other Services" }];

  homeServiceData = [
    { name: "HEAMOGLOBIN" },
    { name: "C.B.C." },
    { name: "E.S.R." },
    { name: "MALARIA TEST (M.P.)" },
    { name: "BLOOD GROUP & RH FACTOR" },
    { name: "PLATELET COUNT" },
    { name: "G6PD" },
    { name: "SICKLING TEST" },
    { name: "PROTHROMBIN TIME/PTT" },
    { name: "BLEEDING & CLOTTING TIME" },
    { name: "BLOOD SUGAR FASTING" },
    { name: "BLOOD SUGAR POST LUNCH" },
    { name: "BLOOD SUGAR RANDOM" },
    { name: "G.T.T.(4 SAMPLE)" },
    { name: "BLOOD UREA" },
    { name: "BUN" },
    { name: "SERUM CREATININE" },
    { name: "SERUM ELECTROLYTE" },
    { name: "R.F.T." },
    { name: "TOTAL PROTEIN" },
    { name: "URIC ACID" },
    { name: "ALBUMINE/GLOBUMINE" },
    { name: "SERUM ELECTROLYTE" },
    { name: "ALKALINE PHOSPHATE" },
    { name: "S.G.O.T." },
    { name: "S.G.P.T." },
    { name: "BILIRUBINE" },
    { name: "L.F.T." },
    { name: "C.P.K.-MB" },
    { name: "C.P.K.-TOTAL" },
    { name: "CARDIAC PROFILE" },
    { name: "TOTAL CHOLESTEROL" },
    { name: "HDL CHOLESTEROL" },
    { name: "S.G.P.T." },
    { name: "TRIGLYCERIDE" },
    { name: "LIPID PROFILE" },
    { name: "G.G.T." },
    { name: "SERUM AMYLASE" },
    { name: "CALCIUM" },
    { name: "PHOSPHORUS" },
    { name: "MAGNESIUM" },
    { name: "IRON & TIBC" },
    { name: "R.A. TEST" },
    { name: "WIDAL TEST" },
    { name: "V.D.R.L. TEST" },
    { name: "SEMEN ANALYSIS" },
    { name: "HBsAG" },
    { name: "HIV" },
    { name: "HCV" },
    { name: "MANTOUX TEST" },
    { name: "COOMB TEST (DIRECT/INDIRECT)" },
    { name: "WESTERN BLOT TEST" },
    { name: "HLA B-27" },
    { name: "Beta HCG" },
    { name: "TROP T" },
    { name: "T.P.H.A." },
    { name: "T3.T4.TSH" },
    { name: "LH" },
    { name: "FSH" },
    { name: "PROLACTINE" },
    { name: "TOXOPLASMA" },
    { name: "A.S.O. TITRE" },
    { name: "C REACTIVE PROTEIN (CRP)" },
    { name: "SPUTUM A.F.B." },
    { name: "DENGUE IgM/ IgG" },
    { name: "DENGUE NS1" },
    { name: "LEPTOSPIRA IgG/ IgM" },
    { name: "MALERIA ANTIGEN" },
    { name: "IGM" },
    { name: "25-OH Vitamin D" },
    { name: "CA 15.3" },
    { name: "CA 19.9" },
    { name: "CA 125" },
    { name: "G6PD" },
    { name: "Hb1AC" },
    { name: "IRON" },
    { name: "VITAMIN B 12" },
    { name: "URINE ROUTINE" },
    { name: "URINE CULTURE & SENSITIVITY" },
    { name: "PREGNANCY TEST" },
    { name: "URINE SUGAR F/PP" },
    { name: "STOOL ROUTINE" },
    { name: "STOOL CULTURE & SENSITIVITY" },
    { name: "DIABETIC PROFILE" },
    { name: "HYPERTENSION PROFILE" },
    { name: "INFERTILITY PROFILE" },
    { name: "PREGNANCY PROFILE" },
    { name: "TROP I" },
    { name: "LIPOPROTEIN - A" },
    { name: "CRP - HS" },
    { name: "OTHERS" }
  ];
  constructor() { }

}